openapi: 3.0.1
info:
  contact:
    email: zkong@gsma.com
    name: Zhen Kong
  description: This is the REST api specification for the Common-adapter layer
  title: Common-Adapter
  version: 0.0.1
servers:
- url: /api/v1/
tags:
- description: Receive Notification From Offchain Comms
  name: event
- description: Access to Contract Object
  name: contract
- description: Access to Signature of Contract
  name: signature
- description: Access to Usage of Contract
  name: usage
- description: Access to Settlement of Contract
  name: settlement
- description: Access to API status information
  name: status
- description: Access to discovery information
  name: discovery
paths:
  /discovery/msps:
    get:
      description: Show a list of all MSPs
      operationId: getDiscoveryMSPs
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: A list of all discovered MSPs
        "500":
          content: {}
          description: Internal Error
      tags:
      - discovery
      x-eov-operation-handler: controllers/DiscoveryController
  /discovery/msps/{mspid}:
    get:
      description: Show details for a specific MSP
      operationId: getDiscoveryMSP
      parameters:
      - description: Name of a MSP
        explode: false
        in: path
        name: mspid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: Details about the requested MSP
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - discovery
      x-eov-operation-handler: controllers/DiscoveryController
  /status:
    get:
      description: Show version information of the API
      operationId: getApiStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: The status of the service
        "500":
          content: {}
          description: Internal Error
      tags:
      - status
      x-eov-operation-handler: controllers/StatusController
  /contracts/event/:
    post:
      description: Webhook callback
      operationId: eventReceived
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
        description: Webhook event Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          description: Successful operation, returns Status message
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - event
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/EventController
  /contracts/:
    get:
      description: Show a list of all Contracts
      operationId: getContracts
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: The status of the service
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
    post:
      description: Create a new Contract
      operationId: createContract
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractRequest'
        description: Contract Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractResponse'
          description: Successful operation, returns created Contract Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/ContractController
  /contracts/{contractID}:
    delete:
      description: Delete a Contract By its ID
      operationId: deleteContractByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractResponse'
          description: The Deleted Conctact Object
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
    get:
      description: Get a Contract By its ID
      operationId: getContractByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: Response format, defaults to JSON if not passed.
        explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - JSON
          - RAW
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ContractResponse'
                - $ref: '#/components/schemas/RAWContractResponse'
                x-content-type: application/json
          description: The Selected Contract Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
    put:
      description: Update existing Contract
      operationId: updateContractByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContractRequest'
        description: Contract Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractResponse'
          description: Successful operation, returns updated Contract Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/ContractController
  /contracts/{contractID}/send/:
    put:
      description: Set State to "SEND" and POST to Blochain adapter towards TargetMSP
        of the Contract
      operationId: sendContractByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractResponse'
          description: Successful operation, returns sent Contract Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - contract
      x-eov-operation-handler: controllers/ContractController
  /contracts/{contractID}/signatures/:
    get:
      description: Get All signatures of a given Contract
      operationId: getSignatures
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: List of available Signatures
        "500":
          content: {}
          description: Internal Error
      tags:
      - signature
      x-eov-operation-handler: controllers/SignatureController
  /contracts/{contractID}/signatures/{signatureID}:
    get:
      description: Get Signature Object by its ID
      operationId: getSignatureByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Signature ID
        explode: false
        in: path
        name: signatureID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureResponse'
          description: The Selected Signature Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - signature
      x-eov-operation-handler: controllers/SignatureController
    put:
      description: Update Signature Object by its ID
      operationId: updateSignatureByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Signature ID
        explode: false
        in: path
        name: signatureID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignatureRequest'
        description: Signature Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignatureResponse'
          description: Successful operation, returns updated Signature Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - signature
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/SignatureController
  /contracts/{contractID}/usages/:
    get:
      description: Get All usage of a given Contract
      operationId: getUsages
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: List of available Usages
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-eov-operation-handler: controllers/UsageController
    post:
      description: Create a new Usage
      operationId: createUsage
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsageRequest'
        description: Usage Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageResponse'
          description: Successful operation, returns created Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UsageController
  /contracts/{contractID}/usages/{usageID}:
    delete:
      description: Delete a Usage By its ID
      operationId: deleteUsageByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Usage ID
        explode: false
        in: path
        name: usageID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageResponse'
          description: The Deleted Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-eov-operation-handler: controllers/UsageController
    get:
      description: Get Usage Object by its ID
      operationId: getUsageByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Usage ID
        explode: false
        in: path
        name: usageID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageResponse'
          description: The Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-eov-operation-handler: controllers/UsageController
    put:
      description: Update Usage Object by its ID
      operationId: updateUsageByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Usage ID
        explode: false
        in: path
        name: usageID
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsageRequest'
        description: Usage Object Payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageResponse'
          description: Successful operation, returns updated Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/UsageController
  /contracts/{contractID}/usages/{usageID}/send/:
    put:
      description: Set State to "SEND" and POST to Blochain adapter towards TargetMSP
        of the Usage
      operationId: sendUsageByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Usage ID
        explode: false
        in: path
        name: usageID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageResponse'
          description: Successful operation, returns sent Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-eov-operation-handler: controllers/UsageController
  /contracts/{contractID}/usages/{usageID}/generate/:
    put:
      description: Generate the "Settlement" with local calculator and POST to Blochain
        adapter towards TargetMSP of the calculated response.
      operationId: generateUsageByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Usage ID
        explode: false
        in: path
        name: usageID
        required: true
        schema:
          type: string
        style: simple
      - description: Defaults to "preview" if not selected. Preview will only performs
          "calculation" and return the calculated settlement in response. if "commit",
          will create the settlement and Send it live to the Blockchain to the targetMSP.
        explode: true
        in: query
        name: mode
        required: false
        schema:
          enum:
          - preview
          - commit
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settlement'
          description: Successful operation, returns sent Usage Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - usage
      x-eov-operation-handler: controllers/UsageController
  /contracts/{contractID}/settlements/:
    get:
      description: Get All Settlement of a given Contract
      operationId: getSettlements
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
          description: List of available Settlements
        "500":
          content: {}
          description: Internal Error
      tags:
      - settlement
      x-eov-operation-handler: controllers/SettlementController
  /contracts/{contractID}/settlements/{settlementID}:
    get:
      description: Get Settlement Object by its ID
      operationId: getSettlementByID
      parameters:
      - description: The contract ID
        explode: false
        in: path
        name: contractID
        required: true
        schema:
          type: string
        style: simple
      - description: The Settlement ID
        explode: false
        in: path
        name: settlementID
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Settlement'
          description: The Settlement Object
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400ErrorResponse'
          description: Bad Request
        "500":
          content: {}
          description: Internal Error
      tags:
      - settlement
      x-eov-operation-handler: controllers/SettlementController
components:
  schemas:
    Event:
      title: Event JSON
      type: object
    ContractResponse:
      additionalProperties: false
      example:
        contractID: 05552c4c-e52f-4bb5-83d2-f50c86115bc8
        header: '{}'
        state: DRAFT
        body:
          key: '{}'
      properties:
        contractID:
          description: ContractID in GUID format
          example: 05552c4c-e52f-4bb5-83d2-f50c86115bc8
          type: string
        header:
          properties:
            name:
              description: Human readable name for the contract.
              example: Contract with XYZ
              type: string
            version:
              description: Version of the contract
              example: "1.0"
              type: string
            type:
              description: Type of document. MUST be "contract"
              enum:
              - contract
              type: string
            fromMSP:
              properties:
                mspid:
                  description: MSPID of the contract creator.
                  example: DTAG
                  type: string
                signatures:
                  items:
                    $ref: '#/components/schemas/SignatureBase'
                  minItems: 1
                  type: array
              type: object
            toMSP:
              properties:
                mspid:
                  description: MSPID of the contract creator.
                  example: TMUS
                  type: string
                signatures:
                  items:
                    $ref: '#/components/schemas/SignatureBase'
                  minItems: 1
                  type: array
              type: object
          required:
          - fromMSP
          - toMSP
          - type
          - version
        body:
          additionalProperties: true
          type: object
        state:
          description: The State of the Contract.
          enum:
          - DRAFT
          - PENDING
          - SENT
          - RECEIVED
          type: string
      required:
      - body
      - contractID
      - header
      - state
      title: Contract JSON
      type: object
    RAWContractResponse:
      additionalProperties: false
      properties:
        contractID:
          description: ContractID in GUID format
          example: 05552c4c-e52f-4bb5-83d2-f50c86115bc8
          type: string
        raw:
          description: Original Base64 encoded RAW payload, Used for Hash calculation
            or Signing.
          example: eyJoZWFkZXIiOnsidmVyc2lvbiI6IjEuM....
          type: string
        state:
          description: The State of the Contract.
          enum:
          - DRAFT
          - PENDING
          - SENT
          - RECEIVED
          type: string
      required:
      - contractID
      - raw
      - state
      title: Contract RAW
      type: object
    ContractRequest:
      additionalProperties: false
      example:
        header:
          fromMSP:
            mspid: DTAG
            signatures:
            - role: role
              name: name
              id: id
            - role: role
              name: name
              id: id
          name: Contract with XYZ
          toMSP:
            mspid: TMUS
            signatures:
            - role: role
              name: name
              id: id
            - role: role
              name: name
              id: id
          type: contract
          version: "1.0"
        body:
          key: '{}'
      properties:
        header:
          $ref: '#/components/schemas/ContractRequest_header'
        body:
          additionalProperties: true
          type: object
      required:
      - body
      - header
      title: Contract JSON for POST/PUT
      type: object
    SignatureBase:
      example:
        role: role
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        role:
          type: string
      type: object
    SignatureResponse:
      additionalProperties: false
      example:
        signature: signature
        extra: '{"name":"john doe", "role":"manager"}'
        certificate: |-
          -----BEGIN CERTIFICATE-----
          MIICYjCCAemgAwIBA...
        signatureID: XXXXXX
        algorithm: secp384r1
      properties:
        signatureID:
          description: signatureID from \"contract"->\"signature\"->\"\<MSPID\>\"[X]->\"id\"
          example: XXXXXX
          type: string
        algorithm:
          description: The algorithm used to sign
          example: secp384r1
          type: string
        certificate:
          description: The certificate of the signer in pem format
          example: |-
            -----BEGIN CERTIFICATE-----
            MIICYjCCAemgAwIBA...
          type: string
        signature:
          description: The digital signature over the document
          type: string
        extra:
          description: Additional Key/Value from \"contract"->\"signature\"->\"\<MSPID\>\"[X]->XXX,
            eg name, role
          example: '{"name":"john doe", "role":"manager"}'
          type: object
      required:
      - algorithm
      - certificate
      - extra
      - signature
      - signatureID
      title: Signature JSON
      type: object
    SignatureRequest:
      additionalProperties: false
      example:
        signature: signature
        certificate: |-
          -----BEGIN CERTIFICATE-----
          MIICYjCCAemgAwIBA...
        algorithm: secp384r1
      properties:
        algorithm:
          description: The algorithm used to sign
          example: secp384r1
          type: string
        certificate:
          description: The certificate of the signer in pem format
          example: |-
            -----BEGIN CERTIFICATE-----
            MIICYjCCAemgAwIBA...
          type: string
        signature:
          description: The digital signature over the document
          type: string
      required:
      - algorithm
      - certificate
      - signature
      title: Signature JSON for PUT
      type: object
    UsageResponse:
      example:
        usageID: 05552c4c-e52f-4bb5-83d2-f50c86115bc8
        header:
          name: Usage, from ABC to XYZ
          msp:
            key: '{}'
          type: usage
          version: "1.0"
        state: DRAFT
        body:
          key: '{}'
      properties:
        usageID:
          description: usageID in GUID format
          example: 05552c4c-e52f-4bb5-83d2-f50c86115bc8
          type: string
        header:
          $ref: '#/components/schemas/UsageResponse_header'
        body:
          additionalProperties: true
          type: object
        state:
          description: The State of the Usage.
          enum:
          - DRAFT
          - SENT
          - RECEIVED
          type: string
      required:
      - body
      - contractID
      - header
      - state
      title: Usage JSON
      type: object
    UsageRequest:
      example:
        header:
          name: Usage, from ABC to XYZ
          msp:
            key: '{}'
          type: usage
          version: "1.0"
        body:
          key: '{}'
      properties:
        header:
          $ref: '#/components/schemas/UsageResponse_header'
        body:
          additionalProperties: true
          type: object
      required:
      - body
      - header
      title: Usage JSON for POST/PUT
      type: object
    Settlement:
      title: Settlement JSON
      type: object
    SuccessResponse:
      example:
        description: XXXX Operation successful
        status: OK
      properties:
        status:
          description: Outcome of the operation
          example: OK
          type: string
        description:
          description: Description of the operation
          example: XXXX Operation successful
          type: string
      required:
      - status
      title: Success Response JSON
      type: object
    "400ErrorResponse":
      properties:
        error:
          description: a list of pre-defined error names
          example: invalid_request
          type: string
        description:
          description: Text Description of the error
          example: The Request is invalid
          type: string
      required:
      - description
      - error
      title: 400 Error Response JSON
      type: object
    ContractRequest_header_fromMSP:
      example:
        mspid: DTAG
        signatures:
        - role: role
          name: name
          id: id
        - role: role
          name: name
          id: id
      properties:
        mspid:
          description: MSPID of the contract creator.
          example: DTAG
          type: string
        signatures:
          items:
            $ref: '#/components/schemas/SignatureBase'
          minItems: 1
          type: array
      type: object
    ContractRequest_header_toMSP:
      example:
        mspid: TMUS
        signatures:
        - role: role
          name: name
          id: id
        - role: role
          name: name
          id: id
      properties:
        mspid:
          description: MSPID of the contract creator.
          example: TMUS
          type: string
        signatures:
          items:
            $ref: '#/components/schemas/SignatureBase'
          minItems: 1
          type: array
      type: object
    ContractRequest_header:
      example:
        fromMSP:
          mspid: DTAG
          signatures:
          - role: role
            name: name
            id: id
          - role: role
            name: name
            id: id
        name: Contract with XYZ
        toMSP:
          mspid: TMUS
          signatures:
          - role: role
            name: name
            id: id
          - role: role
            name: name
            id: id
        type: contract
        version: "1.0"
      properties:
        name:
          description: Human readable name for the contract.
          example: Contract with XYZ
          type: string
        version:
          description: Version of the contract
          example: "1.0"
          type: string
        type:
          description: Type of document. MUST be "contract"
          enum:
          - contract
          type: string
        fromMSP:
          $ref: '#/components/schemas/ContractRequest_header_fromMSP'
        toMSP:
          $ref: '#/components/schemas/ContractRequest_header_toMSP'
      required:
      - fromMSP
      - toMSP
      - type
      - version
      type: object
    UsageResponse_header:
      example:
        name: Usage, from ABC to XYZ
        msp:
          key: '{}'
        type: usage
        version: "1.0"
      properties:
        name:
          description: Human readable name for the usage.
          example: Usage, from ABC to XYZ
          type: string
        version:
          description: Version of the usage
          example: "1.0"
          type: string
        type:
          description: Type of document. MUST be "usage"
          enum:
          - usage
          type: string
        msp:
          additionalProperties: true
          description: 'Additonal check properties per msp eg, "MSPID": {"minSignatures":
            2}'
          type: object
      required:
      - type
      - version
      type: object
